# Generated by Django 4.0.6 on 2022-08-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'forms_data',
            },
        ),
    ]
